### ISSUE TITLE
HttpDocroot

### ISSUE THREAD

**Issue by JoshHoiland** [cjnz457/httpserver#10]
HttpServer class will create a static instance of HttpDocroot that will have a synchronized accessor method used by each thread's request objects' getResponse method. 
The class should at least:
+ determine if a file exists within the docroot directory
+ provide access to a requested file's bytes

**Comment by NicholasCarter** [comment]
Byte[] is passed if the file passed is in the directory and readable, error is printed to terminal and null is returned if the file is incorrect.
